### ISSUE TITLE
Difference between GeneralizedLinearRegressorCV and GeneralizedLinearRegressor with "alpha_search = True"

### ISSUE THREAD

**Issue by kmedved** [Quantco/glum#465]
Thanks for the amazing package. Getting something on par with Glmnet in Python is a huge step forward for the scientific computing community in python.

I am interested in the the difference between `GeneralizedLinearRegressorCV` and `GeneralizedLinearRegressor` when I pass an 'alpha_search = True' parameter into `GeneralizedLinearRegressor`. I can't tell the difference between the two from the documentation. It seems both are doing a similar alpha search. However, I've noticed they take materially different amounts of time to fit, and yield different results. In both cases I am setting the `l1_ratio` at 0.

Relatedly, is there a way to access the selected alpha parameter from `GeneralizedLinearRegressor` in this usage pattern?

**Comment by lbittarello** [comment]
The documentation needs some fleshing out. :)

`GeneralizedLinearRegressor` with `alpha_search`: Fit a separate GLM for each `alpha` on the regularization path and store all coefficients (cf. [here](https://github.com/Quantco/glum/blob/f241668a17748eddc9ae3fe2089962f40e8a636d/src/glum/_glm.py#L1040)). When predicting, use the last `alpha` on the path, unless [users specify otherwise](https://github.com/Quantco/glum/blob/f241668a17748eddc9ae3fe2089962f40e8a636d/src/glum/_glm.py#L1219). According to [Friedman et al. (2007)](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-1/issue-2/Pathwise-coordinate-optimization/10.1214/07-AOAS131.full), it can be faster to fit the model with your desired `alpha` by a fitting a sequence of GLMs with decreasing penalties than to fit the model directly. This setup doesn't choose an optimal `alpha`.

`GeneralizedLinearRegressorCV`: Use cross-validation to choose the best `alpha`. This setup is somewhat similar to combining scikit-learn's [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) with the `GeneralizedLinearRegressor`. However, it uses the regularization path to speed up fitting.

`GeneralizedLinearRegressorCV` is slower of course, because it fits `#(folds)` different models for each `alpha` on the grid, whereas `GeneralizedLinearRegressor` fits just the one.

**Comment by kmedved** [comment]
Thank you - this is very helpful.
