### ISSUE TITLE
Tweedie loglikelihood with Wrights Bessel function

### ISSUE THREAD

**Issue by lorentzenchr** [Quantco/glum#481]
The normalization _constant_ of the Tweedie loglikelihood is a very complicated function, see `_tweedie_normalization` https://github.com/Quantco/glum/blob/5a2f7c7aac9dbba7de0a1c8d76aa8f046d73ae46/src/glum/_functions.pyx#L340 

Since scipy 1.7, there is the new function https://docs.scipy.org/doc/scipy-1.7.0/reference/generated/scipy.special.wright_bessel.html#scipy.special.wright_bessel which should make this computation much easier.
Is currently implemented for the range corresponding to 1<power<2.

This could potentially be a more stable approach for values of the Tweedie power close to 2 or 1.

**Comment by MarcAntoineSchmidtQC** [comment]
Thanks for the suggestion!
I ran a quick test to see if this would improve the stability and I found the opposite. Currently, the code in glum is computing the log of wright-bessel function. Each component is already expressed in logs and therefore it has no issue computing the result for values of the Tweedie power close to 1 or 2.

On the other hand, the wright-bessel function implementation in scipy is not expressed in logs. For values of the tweedie power close to 1 or 2, this leads to massive numbers and overflows (e.g. with a power of 1.99 and a `y` value of 6, the wright-bessel function evaluates to `1.7024896558377077e+44`).

Here's the code that creates the same output as the `_tweedie_normalization` function but uses `scipy.special.wright_bessel`:

```python
def tweed_norm(y, power, dev):
    alpha = (2 - power) / (1 - power)
    wb = wright_bessel(-alpha, 0, (power - 1)**alpha / (2 - power) / y**alpha) / dev**(1 - alpha)
    return np.log(wb) - np.log(y)
```

(I've shamelessly used [your comment here ](https://github.com/statsmodels/statsmodels/issues/7310#issuecomment-873421392)to quickly check that the two implementations gave the same answers and they do.)

Is there a better way to use the scipy function in our code and not run into overflow errors for Tweedie powers close to 1 or 2? The wright-bessel scipy function is slower than our cython implementation to compute a scalar value, but it is natively vectorized so it might be faster if we vectorize some part of the likelihood.

@lbittarello, since you implemented our cython code, do you have any other arguments I didn't cover for or against this suggestion?

**Comment by lorentzenchr** [comment]
> When I originally implemented the series approximation, scipy.special.wright_bessel wasn't available. 🤷‍♀️

This poor function needed a dedicated implementer first. Poor guy :wink: Now, I'm not sure, if that was the best idea. The advantage was that it is mentioned in https://dlmf.nist.gov/10.46#E1 and therefore was easier to include in scipy. But it is more general than what's needed for the Tweedie log-likelihood.

However, I get (`_tweedie_normalization` replaced by pure python version, see details)
```python
y = 6
power = 1.99
dispersion = 1

_tweedie_normalization(y, power, dispersion), tweed_norm(y, power, dispersion)
```
```
(100.05407630566685, 100.05407630566678)
```
Relative precision is 6e-16. Starting from `power >=1.999`, I indeed get `nan`. Maybe this could be improved in scipy?

In the end, if the current code works fine, there is no need to change it. Some more unit tests could help to get more trust.

<details>

```python
from math import ceil, exp, floor, log
import numpy as np
from scipy.special import loggamma, wright_bessel


def tweed_norm(y, power, dev):
    alpha = (2 - power) / (1 - power)
    wb = wright_bessel(-alpha, 0, (power - 1)**alpha / (2 - power) / y**alpha) / dev**(1 - alpha)
    return np.log(wb) - np.log(y)

def _tweedie_normalization(y, power, dispersion):

    j_max = exp((2 - power) * log(y) - log(dispersion) - log(2 - power))
    w_max = _log_w_j(y, power, dispersion, j_max)
    w_summand = 0.0

    j_lower, j_upper = _sum_limits(y, power, dispersion, j_max)

    for j in range(j_lower, j_upper + 1):
        w_summand += exp(_log_w_j(y, power, dispersion, j) - w_max)

    return w_max + log(w_summand) - log(y)

def _sum_limits(y, power, dispersion, j_max):

    w_lower = 0
    j_lower = 1.0
    j_upper = ceil(j_max)
    w_upper = _log_w_j(y, power, dispersion, j_upper)

    w_crt = _log_w_j(y, power, dispersion, j_max) - 37
    w_one = _log_w_j(y, power, dispersion, 1)

    if w_one <= w_crt:
        j_lower = floor(j_max)
        w_lower = _log_w_j(y, power, dispersion, j_lower)
        while w_lower >= w_crt:
            j_lower -= 1
            w_lower = _log_w_j(y, power, dispersion, j_lower)
    while w_upper >= w_crt:
        j_upper += 1
        w_upper = _log_w_j(y, power, dispersion, j_upper)

    return int(j_lower), int(j_upper)

def _log_w_j(y, power, dispersion, j):
    alpha = (2 - power) / (1 - power)
    return j * _log_z(y, power, dispersion) - loggamma(1 + j) - loggamma(-alpha * j)

def _log_z(y, power, dispersion):
    alpha = (2 - power) / (1 - power)
    return (
        alpha * log(power - 1)
        - alpha * log(y)
        - (1 - alpha) * log(dispersion)
        - log(2 - power)
    )
```

</details>
