### ISSUE TITLE
Use pixi for setting up the dev environment

### ISSUE THREAD

**Issue by stanmart** [Quantco/glum#801]
At the moment, the [contribution guidelines](https://glum.readthedocs.io/en/latest/contributing.html) suggest setting up a conda environment based on the `environment.yml` files in the repo. I think there is quite a lot to gain from moving to pixi in the case of glum. In particular:

 - There are various `environment.yml` files for different use cases. Pixi has an elegant way of handling [multiple environments](https://pixi.sh/latest/features/multi_environment/)
 - Certain dependencies are platform specicfic, which pixi also [handles nicely](https://pixi.sh/latest/features/multi_platform_configuration/) (see #787)
 - It uses [lockfiles](https://pixi.sh/latest/features/lockfile/), which would help ensure that everyone (including the CI) uses the same versions of the dependencies. Especially useful for benchmarking.
 - I personally find it more ergonomic than activating environments but YMMV

What would not change:

 - Pixi still uses conda packages for dependencies
 - The build system. Pixi can not build conda packages (yet?). CI conda builds would still be based on `conda.recipe/meta.yaml` and  `conda-mambabuild`, and PyPI builds on `cibuildwheel`.

I can make a draft PR so we get a better idea how it would look like. What do you think?

**Comment by jtilly** [comment]
I'm in favor of moving things to pixi. This is a nice repo to try things out. 

It would be great if we could address the following items:
- we need to regularly (and automatically) update the lockfiles so that we're testing against the most recent versions of our dependencies
- we should also add a test against "oldies", i.e. the minimal dependencies that we want to support
- it would be nice if we could get the tests against [nightlies](https://github.com/Quantco/glum/blob/15dda3b72ffc3c31bf151244f67046deb2e48305/.github/workflows/daily.yml#L37-L51) also included in the pixi setup

**Comment by stanmart** [comment]
Good points. Let's continue under #802
